name: Rust - added by github

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd replacetxt
        cargo build --verbose
    - name: Run tests
      run: |
        cd replacetxt
        cargo test --verbose
